Update logBackupper
-Added error logs
-Changed time formatting for logs
-Fixed if caution from break to continue
-Added comments
-Added exec errout

diff --git a/logBackupper b/logBackupper
--- a/logBackupper
+++ b/logBackupper
@@ -1,6 +1,8 @@
 #!/bin/bash
 saveloc="/var/backups/logBackupper";
 d=`date +%m-%d-%Y`
+printf "Error log for %(%F %T)T\n\n" >> $saveloc/error/error_log_$d.txt;
+exec 2>> $saveloc/error/error_log_$d.txt
 if [ "$EUID" -ne 0 ]
 then
         printf "[\033[1;33mCaution\033[0m] Superuser not detected. Run this script with sudo to avoid permission errors. [\033[1;33mCaution\033[0m]\n";
@@ -20,29 +22,36 @@ echo "Insert location to be backed up: ";
 read loc
 if [[ "$loc" == /* || "$loc" == ./* || "$loc" == ~/* ]];
 then
-        break   #echo "$loc is an absolute path";
+        continue        #If path is absolute continue
 else
-        loc=$(realpath $loc);
-        #echo "$loc";
+        loc=$(realpath $loc); #If path is relative, change to absolute
 fi
+
 printf "Searching for log files in $loc"
 
 if ls ${loc}/*.log* &>/dev/null;
 then
         sleep 1;
-        printf " [\033[1;32mFound\033[0m]\n";
-        printf "\nHashed on %(%F)T\n\n" >> $saveloc/hashed_logs.txt;
+        printf " [\033[1;32mFound\033[0m]\n"; #Green Found
+        printf "\nHashed on %(%F %T)T\n\n" >> $saveloc/hashed_logs.txt;
         for f in $loc/*.log*
         do
-                b=$(basename -- "$f")
-                #echo "${b%.*}"
-                cp $f $saveloc/logs/${b%.*}-$d.log
+               if [ $? -eq 0 ]; then
+                b=$(basename -- "$f") #converts f to name of file
+                printf "$f \t[\033[1;32mOK\033[0m]\n";
+                cp $f $saveloc/logs/${b%.*}-$d.log #Removes path in backup and names as filename.log-DD-MM-YYYY
                 md5sum $f >> $saveloc/hashed_logs.txt
+                else
+                        printf "$f [\033[0;30mError\033[0m]\n";
+                        printf "$f" 2>> $saveloc/error/error_log_$d.txt;
+                fi
         done
 else
         sleep 2;
         printf " [\033[0;31mFailed\033[0m]\n"
+        printf "Error - No log files found in $loc\n" >> $saveloc/error/error_log_$d.txt;
         echo "No log files exist!";
         sleep 1;
         echo "Shutting down..";
+        exit 1;
 fi
